### ISSUE TITLE
Is that valid to use these attribute notations in MARS dataset?

### ISSUE THREAD

**Issue by Hellomodo** [vana77/Market-1501_Attribute#10]
Hi @vana77 , thanks for your wonderful work！

Since the MARS dataset is an extension of the Market-1501, does that mean your attribute notations also work for MARS dataset?

**Comment by vana77** [comment]
Hi @Hellomodo 
Sure, the attribute annotation is also work for MARS. The id of two datasets are the same, however the train/test split is different. So you might first match the attribute to the MARS dataset.
