### ISSUE TITLE
The query folder of Market-1501 for what?

### ISSUE THREAD

**Issue by ciwei123** [vana77/Market-1501_Attribute#11]
@vana77 ,Hi,I can not understand the query folder,gt_query folder and gr_bbox,those for what ?Thank you! and forget my poor English.

**Comment by layumi** [comment]
Hi @ciwei123,
Just for a quick explanation,
- `gt_query` is for multiple-query evaluation.
- `gt_bbox` is for detection quality evaluation.

More details can be found at http://www.liangzheng.com.cn/Project/project_reid.html.
```
4) "gt_query". This folder contains the ground truth annotations. For each query, the relevant images are marked as "good" or "junk". "junk" has zero impact on search accuracy. "junk" images also include those in the same camera with the query.
5) "gt_bbox". We also provide the hand-drawn bounding boxes. They are used to judge whether a DPM bounding box is good. 
```

**Comment by ciwei123** [comment]
@layumi Thanks your reply! That means that   'gt_query' and 'query' are   for evaluate the model, right?
And another question, I have trained a reid model 'model.ckpt-300000', how I evaluate the model? Thank you again!!

**Comment by layumi** [comment]
Which framework did you use? 
I do not know with the `ckpt` file.

If you use python, especially pytorch, you may refer to https://github.com/layumi/Person_reID_baseline_pytorch/blob/master/evaluate.py
If you use matlab, you may refer to 
https://github.com/layumi/2016_person_re-ID/tree/master/evaluation

**Comment by ciwei123** [comment]
@layumi Thank you very much! And I have learned your "tutorial", that is very useful .Thank you again.Now, I have an another question.I have trained the model from "https://github.com/nwojke/cosine_metric_learning" , and this link code have created "query.mat" and "test.mat",  but when I evaluate the model ,I need a ”query_max.mat“ file.How I can get the file according the "query.mat"? Looking for your reply.

**Comment by layumi** [comment]
Why you need a 'query_max.mat'? 
You want to conduct a multiple-query evaluation?

**Comment by ciwei123** [comment]
@layumi Yes! I want to conduct a multiple-query evaluation. Because I see the following paragraph：" While the single-gallery-shot CMC is well defined, it does not have a common agreement when it comes to the multi-gallery-shot setting, where each gallery identity could have multiple instances. " Could you help me get the "query_max.mat" file according the "query.mat" ? Looking for your reply.Thank you very much.

**Comment by layumi** [comment]
@ciwei123 
Please check the original code of Market-1501. It includes a code for multiple-query evaluation http://www.liangzheng.org/Project/project_reid.html , which generates `query_max` and `query_avg`.

**Comment by ciwei123** [comment]
@layumi Thank you .You really give me a lot of help. I want to combine a REID code for my tracking, I find a REID code Rank 1=79.1, mAP=56.68 in Market-1501. I want to find a better performance code. Could you give me some advice about REID open source ？Thank you very much!

**Comment by layumi** [comment]
If you want to use matlab, you may check this link (https://github.com/layumi/Person_reID_baseline_matconvnet).
If you want to use python, please check this (https://github.com/layumi/Person_reID_baseline_pytorch).

**Comment by ciwei123** [comment]
@layumi I will study it .I don't know how to express my gratitude. If I can help you something, please contact me.Thank you again.
