### ISSUE TITLE
The attribute label seems not so accuracy.

### ISSUE THREAD

**Issue by scc-zju** [vana77/Market-1501_Attribute#12]
As shown in following picture, the label indicates that the person doesn't have a bag. But it seems that the person has a bag.
The age seems like adult instead of teenager.
The upper-body clothing seems like pink instead of white.
![image](https://user-images.githubusercontent.com/46096165/53017378-c5ca2000-348a-11e9-8d19-40de6bb921b7.png)

**Comment by layumi** [comment]
Hi @scc-zju ,

Sorry for our mistake.
In this README, we start from 1. In the data, we start from 0. 
You may refer to this table in the README, which is consistent with this image.

| attribute | representation in file | label |
| :----: | :----: | :----: |
| gender | gender | male(1), female(2) |
| hair length | hair| short hair(1), long hair(2)    |
| sleeve length | up | long sleeve(1), short sleeve(2) |
| length of lower-body clothing | down | long lower body clothing(1), short(2)    |
| type of lower-body clothing| clothes| dress(1), pants(2)    |
| wearing hat| hat | no(1), yes(2) |
| carrying backpack| backpack | no(1), yes(2) |
| carrying bag| bag | no(1), yes(2) |
| carrying handbag| handbag | no(1), yes(2) |
| age| age | young(1), teenager(2), adult(3), old(4) |
| 8 color of upper-body clothing| upblack, upwhite, upred, uppurple, upyellow, upgray, upblue, upgreen | no(1), yes(2) |
| 9 color of lower-body clothing| downblack, downwhite, downpink, downpurple, downyellow, downgray, downblue, downgreen,downbrown | no(1), yes(2) |

**Comment by ajithvcoder** [comment]
@scc-zju @vana77 @layumi  how to download the dataset ? where is the link

**Comment by vana77** [comment]
Hi @ajithvallabai , please refer to http://zheng-lab.cecs.anu.edu.au/Project/project_reid.html

**Comment by ajithvcoder** [comment]
thanks @vana77
