### ISSUE TITLE
24 attributes in APR paper

### ISSUE THREAD

**Issue by draculayuan** [vana77/Market-1501_Attribute#13]
Thanks for the work! I came across the original paper and it seems that only 24 attributes are used in the APR paper, but the dataset has 27 attributes in total. I tried to look through the paper and see if there's any specific reasons for it and did not managed to find any. May I kindly check what are the 3 attributes that are not used and if I am supposed to throw out those attributes when doing experiments?

Thank you!

**Comment by draculayuan** [comment]
Sorry for the spam, I read through the evaluation matlab tool, seems like all 27 attributes are used. But it seems like for the upper clothes color and lower clothes color, the tool did not consider the case where the color is not in the 8/9 colors (means the label will be all 1 for upper or lower colors), may I know if you mind helping me to see if my understanding is wrong? Thank you!

**Comment by vana77** [comment]
Hi @draculayuan , you are right. Sorry for the late reply.
