### ISSUE TITLE
Invalid values for 'up' label

### ISSUE THREAD

**Issue by jmuncaster** [vana77/Market-1501_Attribute#2]
I loaded gallery_market.mat and looked at the values in the third column.

The README.md says that the third column contains values for "Sleeve length" (up) and that possible values are ["long sleeve (1)", "short sleeve (2)"] but some of the data has a value of 3.

```
>> load gallery_market.mat
>> sum(gallery(:,3)==3)

ans =

        1234
```

Am I interpreting the data correctly?

Is this the right ordering of attributes?
['gender', 'hair', 'up', 'down', 'clothes', 'hat', 'backpack', 'bag', 'handbag', 'age', 'upcolor', 'downcolor']

Thanks

**Comment by vana77** [comment]
Actually you should use the label in market_attribute.mat.  
gallery_market.mat is just an example output of my code that used for evaluation. In this file, the third column represents the label age. You can refer to the evaluation code evaluate_market_attribute.m to see the detail.
