### ISSUE TITLE
where can i find the train id

### ISSUE THREAD

**Issue by changwuxie** [vana77/Market-1501_Attribute#4]
I have download the dataset and the attribute.mat.  but i can't find the train id and test id.

**Comment by blauigris** [comment]
+1

**Comment by layumi** [comment]
Hi @changwuxie @blauigris ,
Sorry for the late response.
1. The ID label is in the image name.  For example, "0001_c1s1_001051_00.jpg", "0001" is the ID label, "c1" is the first camera (there are totally 6 cameras).
( For more details, you may refer to http://www.liangzheng.org/Project/project_reid.html)
2. The Attribute ID is consistent with the order of the original training set.
