### ISSUE TITLE
Inappropriate color label

### ISSUE THREAD

**Issue by socoolzjm** [vana77/Market-1501_Attribute#5]
I found two images were inappropriately labeled. The color differences are calculated by CIEDE2000. RGB value standards are according to Wikipedia. I randomly picked a 3x3 area and got the mean RGB value followed by converting to L* A* B* space.

[RGB_Pink](https://www.wikiwand.com/en/Shades_of_pink) = [255, 192, 203]; 
[RGB_Purple](https://www.wikiwand.com/en/Shades_of_purple) = [128, 0, 128];
[RGB_Yellow ](https://www.wikiwand.com/en/Yellow)= [255, 255, 0];

1. 0430 in bounding_box_train or 227 in market_attribute.train

It was labeled as downpink = 2.
My results: de_Pink = 65.4, de_Purple = 16.3;

2. 0601 in bounding_box_test or 289 in market_attribute.test

It was labeled as upyellow = 2.
My results: de_Yellow = 85.1, de_Purple = 17.8;

Values were different according to the picked area, but the differences were significantly large.

**Comment by layumi** [comment]
Hi @socoolzjm , sorry for the late response.
Thank you for your report.
We annotate the dataset by hand, which inevitably introduces some annotation error. We will consider to fix it in the final version. @vana77
