### ISSUE TITLE
why  test data(i.e., 13115 x 12 matrix) 

### ISSUE THREAD

**Issue by jpainam** [vana77/Market-1501_Attribute#6]
Hi,
Based on Market-1501 dataset, we have 750 identities for test  and 19,732 test images.
I understand the 12 column values, but why 13115 entries?
Thank you

**Comment by layumi** [comment]
Hi @jpainam , sorry for the late response.
When we do evaluation, we ignore the distractors (images labeled as 0 or -1) in the gallery.
So the number of the left images is 13115.

**Comment by xjhjinhui** [comment]
@jpainam  @layumi Hi, I  am a newbie and sorry to bother you.Could you please tell me the meaning of 12 column values.Looking forward to your reply.
