### ISSUE TITLE
how to sort the images to match the order of labels?

### ISSUE THREAD

**Issue by zyoohv** [vana77/Market-1501_Attribute#7]
How to sort the images to match the images and the labels?

for example, the image: 

"0665_c6s2_041293_01.jpg"

1. we convert the string "0665" to integer 665, than sort them or
2. we sort the the string "0665" in alphabet order.

In 1. "99" < "100" but In 2 "99" > "100".

I want to know which one the author used ?

**Comment by vana77** [comment]
Hi @zyoohv , sorry for the late response. We adopt the second method. 
We have just revised the annotation to contain one more label of image identity. So you can match the images and labels more conveniently.
