### ISSUE TITLE
标签与图片的对应关系

### ISSUE THREAD

**Issue by SigmaLGX** [vana77/Market-1501_Attribute#8]
我修改了作者的matlab代码，将图片地址与标签的对应关系存储成txt文件。 需要的可以下载：
百度网盘：
链接：https://pan.baidu.com/s/1KU8gRgQ6aaHPMXEPt6qcqQ 密码：5wkf

**Comment by layumi** [comment]
Thank you @SigmaLGX

**Comment by Jason-xin** [comment]
@SigmaLGX 感谢你的分享，不过只有test的，请问train的txt文件可否分享？？

**Comment by Jason-xin** [comment]
@SigmaLGX 额，不需要了，刚看到作者说标注的属性是identity级别的，打扰了~
